server:
    port: 8080
    servlet:
        context-path: /api/v1/identity-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
jwt:
  signerKey: "SC4Y5pmxSv8GO24vtdr5zka0P7yOV1TjGHXu0evkIXwdgKQflsRwUl9Fjh3jhcZg"